### ISSUE TITLE
Build fails on Windows

### ISSUE THREAD

**Issue by d00z3l** [DelSkayn/rquickjs#41]
Hi,

I am trying out rquickjs but the build script is failing. I have added it to `rquickjs = "0.1.3"` to cargo.toml.

```
Caused by:
  process didn't exit successfully: `D:\Documents\Projects\src\aaaa\celldb\target\debug\build\rquickjs-sys-f8396077fcf24154\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-env-changed=CARGO_FEATURE_EXPORTS
  cargo:rerun-if-env-changed=CARGO_FEATURE_BINDGEN
  cargo:rerun-if-env-changed=CARGO_FEATURE_UPDATE_BINDINGS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_BYTECODE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_GC
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_GC_FREE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_FREE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_LEAKS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_MEM
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_OBJECTS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_ATOMS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_SHAPES
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_MODULE_RESOLVE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_PROMISE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_READ_OBJECT

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', C:\Users\aaaa\.cargo\registry\src\github.com-1ecc6299db9ec823\rquickjs-sys-0.1.3\build.rs:136:10
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\std\src\panicking.rs:517
     1: core::panicking::panic_fmt
               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\core\src\panicking.rs:101
     2: core::result::unwrap_failed
               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\/library\core\src\result.rs:1617
     3: enum$<core::result::Result<std::process::Child,std::io::error::Error> >::unwrap<std::process::Child,std::io::error::Error>
               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\result.rs:1299
     4: build_script_build::patch<ref$<std::path::Path>,std::path::PathBuf>
               at .\build.rs:131
     5: build_script_build::main
               at .\build.rs:98
     6: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35\library\core\src\ops\function.rs:227
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by d00z3l** [comment]
I worked it out, I need to add a patch program to my path. Git for Windows comes with one so you need to add: `C:\Program Files\Git\usr\bin` (or where ever Git is installed on your computer) to your path.
