### ISSUE TITLE
Classes for structs with lifetime specifiers

### ISSUE THREAD

**Issue by jeromegn** [DelSkayn/rquickjs#60]
Edit: this may have nothing to with the lifetime specifier, but I didn't have issues without them on another class. I manually implemented ClassDef because it doesn't work with the macro when using lifetimes.

I seem to be able to compile something like this:

```rust
    pub struct Transaction<'a> {
        tx: Option<am::transaction::Transaction<'a>>,
    }

    impl<'a> Transaction<'a> {
        pub fn get(&self, prop: Prop) -> Option<ObjId> {
            println!("TRANSACTION GET {:?}", prop.0);
            let tx = self.ensure_tx();
            // from.as_ref().map(|o| &o.obj_id).unwrap_or(&am::ROOT)
            let (value, obj_id) = tx.get(&am::ROOT, prop.0).ok()??;
            Some(ObjId { obj_id, value })
        }

        fn ensure_tx(&self) -> &am::transaction::Transaction<'a> {
            match self.tx {
                None => panic!("no tx! bad!"),
                Some(ref tx) => tx,
            }
        }
    }

    impl<'a> rquickjs::ClassDef for Transaction<'a> {
        const CLASS_NAME: &'static str = "Transaction";
        unsafe fn class_id() -> &'static mut rquickjs::ClassId {
            static mut CLASS_ID: rquickjs::ClassId = rquickjs::ClassId::new();
            &mut CLASS_ID
        }
        const HAS_PROTO: bool = true;
        fn init_proto<'js>(_ctx: rquickjs::Ctx<'js>, proto: &rquickjs::Object<'js>) -> rquickjs::Result<()> {
            proto.set("get", Func::new("get", Method(Transaction::get)))?;
            // proto.set();
            Ok(())
        }
    }
    impl<'js> rquickjs::IntoJs<'js> for Transaction<'js> {
        fn into_js(self, ctx: rquickjs::Ctx<'js>) -> rquickjs::Result<rquickjs::Value<'js>> {
            <Transaction as rquickjs::ClassDef>::into_js_obj(self, ctx)
        }
    }
    impl<'js> rquickjs::FromJs<'js> for &'js Transaction<'js> {
        fn from_js(ctx: rquickjs::Ctx<'js>, value: rquickjs::Value<'js>) -> rquickjs::Result<Self> {
            <Transaction as rquickjs::ClassDef>::from_js_ref(ctx, value)
        }
    }
    impl<'js> rquickjs::FromJs<'js> for &'js mut Transaction<'js> {
        fn from_js(ctx: rquickjs::Ctx<'js>, value: rquickjs::Value<'js>) -> rquickjs::Result<Self> {
            <Transaction as rquickjs::ClassDef>::from_js_mut(ctx, value)
        }
    }
```

However, `get` isn't present in the prototype when I try to evaluate a script _and_ I can't inspect it outside of a script without encountering an `Unknown` error.

```rust
        let rt = Runtime::new().unwrap();
        let ctx = Context::full(&rt).unwrap();
        ctx.with(|ctx| {
            let globals = ctx.globals();
            globals.set("print", Func::new("print", print)).unwrap();

            let tx = doc.transaction();
            globals.set("__doc", Transaction { tx: Some(tx) }.into_js_obj(ctx).unwrap()).unwrap();
            let obj: rquickjs::Object = globals.get("__doc").unwrap();

            let proto: rquickjs::Object = obj.get_prototype().unwrap();
            // ^ Unknown error happens here!

            for p in proto.keys::<String>() {
                println!("key: {:?}", p);
            }

            ctx.eval::<(), _>(
                r#"
                    print("__doc.get: "+__doc.get.toString());
                "#,
            )
            .unwrap();

            println!("done");
        });
```

Backtrace:

```
running 1 test
thread 'js::tests::fun' panicked at 'called `Result::unwrap()` on an `Err` value: Unknown', crates/corrosion/src/js/mod.rs:231:67
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::result::unwrap_failed
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1018:23
   4: corrosion::js::tests::fun::{{closure}}
             at ./src/js/mod.rs:231:47
   5: rquickjs_core::context::Context::with
             at /Users/jerome/.cargo/registry/src/github.com-1ecc6299db9ec823/rquickjs-core-0.1.5/src/context.rs:131:26
   6: corrosion::js::tests::fun
             at ./src/js/mod.rs:224:13
   7: corrosion::js::tests::fun::{{closure}}
             at ./src/js/mod.rs:215:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
```

**Comment by jeromegn** [comment]
My bad. I forgot to register the class via `Class::<Transaction>::register(ctx)`
